version: '3.8'

services:
  chat-bot:
    build: .
    ports:
      - "3000:3000"
    environment:
      - HOST=127.0.0.1
      - DATABASE_URL
      - OPENAI_API_KEY
      - OPENAI_BASE_URL
      - EXA_API_KEY